### ISSUE TITLE
PeriodicController issue with Tsit5 integrator

### ISSUE THREAD

**Issue by tkoolen** [JuliaRobotics/RigidBodySim.jl#68]
```julia
using RigidBodySim, RigidBodyDynamics, Compat.Test

mechanism = rand_tree_mechanism(Float64, Revolute{Float64})
state = MechanismState(mechanism)
controltimes = Float64[]
initialize = (c, u, t, integrator) -> empty!(controltimes)
τ = similar(velocity(state))
Δt = 0.25

controller = PeriodicController(τ, Δt, function (τ, t, state)
    push!(controltimes, t)
    τ .= 0
end; initialize = initialize)

final_time = 25.3
problem = ODEProblem(Dynamics(mechanism, controller), state, (0., final_time))
sol = solve(problem, Tsit5(), abs_tol = 1e-10, dt = 0.05)
@test controltimes == collect(0. : Δt : final_time - rem(final_time, Δt))
```

`Vern7` is fine though. For `Tsit5`, the first time the controller is called when `docontrol[] == true`, the time is not the same as the time at which the callback set `docontrol[]` to true. I believe this is due to a fairly recent DifferentialEquations change, but I haven't narrowed it down to a version yet.

**Comment by ChrisRackauckas** [comment]
I have things all setup for v0.7 now so it's not easy for me to test this. I am not aware of a change which would cause this behavior. Is it floating point error in the times?

**Comment by tkoolen** [comment]
Yeah, I just tested all the way back to DiffEqBase 3.0.1 and OrdinaryDiffEq 3.0.1, and I get the same error. I really thought this was working for Tsit5 at some point, but now it looks like this is just a preexisting bug in my code. I think it's due to the fsal nature of Tsit5. I'm working on a fix.

**Comment by tkoolen** [comment]
Closing this since #73 seems to have done the trick. I'd still like to understand why this happened though.

**Comment by ChrisRackauckas** [comment]
If you modify u it needs to reset fsal on fsal algorithms

**Comment by tkoolen** [comment]
I'm not modifying `u` though. See https://github.com/JuliaRobotics/RigidBodySim.jl/pull/72#issuecomment-408911804.

**Comment by ChrisRackauckas** [comment]
Is this still a thing? Is there an MWE? We changed quite a few things since this was noted, but I kept it in my email and I'm not sure why?

**Comment by tkoolen** [comment]
Yes. The test in the issue description still fails if I undo https://github.com/JuliaRobotics/RigidBodySim.jl/pull/73/commits/a635d9258de9e30c5cfb6f0b2b7446842cc3db98.

**Comment by ChrisRackauckas** [comment]
Interesting. Is the MWE just to use PeriodicController? Or more general? I don't think we have a test which recreates this.
