### ISSUE TITLE
Build failure on julia 1.0.2

### ISSUE THREAD

**Issue by fps** [JuliaRobotics/RigidBodySim.jl#95]
Does the build expect 7z to be on the path?

<pre>
(v1.0) pkg> add RigidBodySim
   Cloning default registries into C:\Users\fschmidt\.julia\registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
 Resolving package versions...
 Installed TreeViews ─────────────────── v0.3.0
 Installed AssetRegistry ─────────────── v0.1.0
 Installed Compat ────────────────────── v1.4.0
 Installed RecursiveArrayTools ───────── v0.18.4
 Installed NLSolversBase ─────────────── v7.1.1
 Installed DiffResults ───────────────── v0.0.3
 Installed OrderedCollections ────────── v1.0.2
 Installed RigidBodySim ──────────────── v1.0.0
 Installed BinaryProvider ────────────── v0.5.3
 Installed Observables ───────────────── v0.2.3
 Installed IniFile ───────────────────── v0.5.0
 Installed LoopThrottle ──────────────── v0.0.3
 Installed MechanismGeometries ───────── v0.1.2
 Installed MacroTools ────────────────── v0.4.4
 Installed NaNMath ───────────────────── v0.3.2
 Installed DiffEqBase ────────────────── v4.31.0
 Installed SpecialFunctions ──────────── v0.7.2
 Installed ExponentialUtilities ──────── v1.3.0
 Installed CoordinateTransformations ─── v0.5.0
 Installed DiffEqCallbacks ───────────── v2.3.0
 Installed WebIO ─────────────────────── v0.4.2
 Installed Widgets ───────────────────── v0.4.3
 Installed DiffBase ──────────────────── v0.3.2
 Installed MbedTLS ───────────────────── v0.6.6
 Installed FunctionalCollections ─────── v0.4.0
 Installed Blink ─────────────────────── v0.8.1
 Installed Reexport ──────────────────── v0.2.0
 Installed HTTP ──────────────────────── v0.7.1
 Installed BinDeps ───────────────────── v0.8.10
 Installed Parameters ────────────────── v0.10.2
 Installed ColorTypes ────────────────── v0.7.5
 Installed Rotations ─────────────────── v0.9.1
 Installed AxisAlgorithms ────────────── v0.3.0
 Installed CSSUtil ───────────────────── v0.1.0
 Installed IterTools ─────────────────── v1.1.1
 Installed Hiccup ────────────────────── v0.2.2
 Installed Distances ─────────────────── v0.7.3
 Installed Mustache ──────────────────── v0.5.8
 Installed WebSockets ────────────────── v1.1.0
 Installed Interpolations ────────────── v0.10.6
 Installed Pidfile ───────────────────── v1.1.0
 Installed MeshIO ────────────────────── v0.3.1
 Installed DataStructures ────────────── v0.14.0
 Installed Mux ───────────────────────── v0.5.3
 Installed OrdinaryDiffEq ────────────── v4.17.2
 Installed JSExpr ────────────────────── v0.3.1
 Installed DiffEqOperators ───────────── v3.4.0
 Installed RecipesBase ───────────────── v0.6.0
 Installed DiffEqDiffTools ───────────── v0.7.1
 Installed MsgPack ───────────────────── v0.2.0
 Installed Calculus ──────────────────── v0.4.1
 Installed MuladdMacro ───────────────── v0.2.1
 Installed StaticArrays ──────────────── v0.10.0
 Installed GeometryTypes ─────────────── v0.7.1
 Installed LightXML ──────────────────── v0.8.0
 Installed GenericSVD ────────────────── v0.2.0
 Installed Tables ────────────────────── v0.1.11
 Installed ForwardDiff ───────────────── v0.10.1
 Installed InteractBase ──────────────── v0.8.1
 Installed NLsolve ───────────────────── v3.0.1
 Installed Requires ──────────────────── v0.5.2
 Installed OffsetArrays ──────────────── v0.9.0
 Installed WoodburyMatrices ──────────── v0.4.1
 Installed TypeSortedCollections ─────── v1.0.0
 Installed MeshCat ───────────────────── v0.4.0
 Installed FileIO ────────────────────── v1.0.4
 Installed LineSearches ──────────────── v7.0.1
 Installed Knockout ──────────────────── v0.2.0
 Installed Ratios ────────────────────── v0.3.0
 Installed Lazy ──────────────────────── v0.13.2
 Installed Measures ──────────────────── v0.3.0
 Installed CommonSubexpressions ──────── v0.2.0
 Installed MeshCatMechanisms ─────────── v0.2.1
 Installed JSON ──────────────────────── v0.20.0
 Installed Roots ─────────────────────── v0.7.4
 Installed FixedPointNumbers ─────────── v0.5.3
 Installed DiffRules ─────────────────── v0.0.7
 Installed IteratorInterfaceExtensions ─ v0.1.1
 Installed TableTraits ───────────────── v0.4.0
 Installed URIParser ─────────────────── v0.4.0
 Installed Colors ────────────────────── v0.9.5
 Installed DocStringExtensions ───────── v0.5.0
 Installed RigidBodyDynamics ─────────── v1.2.0
  Updating `C:\Users\fschmidt\.julia\environments\v1.0\Project.toml`
  [e61f16d8] + RigidBodySim v1.0.0
  Updating `C:\Users\fschmidt\.julia\environments\v1.0\Manifest.toml`
  [bf4720bc] + AssetRegistry v0.1.0
  [13072b0f] + AxisAlgorithms v0.3.0
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.3
  [ad839575] + Blink v0.8.1
  [70588ee8] + CSSUtil v0.1.0
  [49dc2e85] + Calculus v0.4.1
  [3da002f7] + ColorTypes v0.7.5
  [5ae59095] + Colors v0.9.5
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v1.4.0
  [150eb455] + CoordinateTransformations v0.5.0
  [864edb3b] + DataStructures v0.14.0
  [c5cfe0b6] + DiffBase v0.3.2
  [2b5f629d] + DiffEqBase v4.31.0
  [459566f4] + DiffEqCallbacks v2.3.0
  [01453d9d] + DiffEqDiffTools v0.7.1
  [9fdde737] + DiffEqOperators v3.4.0
  [163ba53b] + DiffResults v0.0.3
  [b552c78f] + DiffRules v0.0.7
  [b4f34e82] + Distances v0.7.3
  [ffbed154] + DocStringExtensions v0.5.0
  [d4d017d3] + ExponentialUtilities v1.3.0
  [5789e2e9] + FileIO v1.0.4
  [53c48c17] + FixedPointNumbers v0.5.3
  [f6369f11] + ForwardDiff v0.10.1
  [de31a74c] + FunctionalCollections v0.4.0
  [01680d73] + GenericSVD v0.2.0
  [4d00f742] + GeometryTypes v0.7.1
  [cd3eb016] + HTTP v0.7.1
  [9fb69e20] + Hiccup v0.2.2
  [83e8ac13] + IniFile v0.5.0
  [d3863d7c] + InteractBase v0.8.1
  [a98d9a8b] + Interpolations v0.10.6
  [c8e1da08] + IterTools v1.1.1
  [82899510] + IteratorInterfaceExtensions v0.1.1
  [97c1335a] + JSExpr v0.3.1
  [682c06a0] + JSON v0.20.0
  [bcebb21b] + Knockout v0.2.0
  [50d2b5c4] + Lazy v0.13.2
  [9c8b4983] + LightXML v0.8.0
  [d3d80556] + LineSearches v7.0.1
  [39f5be34] + LoopThrottle v0.0.3
  [1914dd2f] + MacroTools v0.4.4
  [739be429] + MbedTLS v0.6.6
  [442fdcdd] + Measures v0.3.0
  [931e9471] + MechanismGeometries v0.1.2
  [283c5d60] + MeshCat v0.4.0
  [6ad125db] + MeshCatMechanisms v0.2.1
  [7269a6da] + MeshIO v0.3.1
  [99f44e22] + MsgPack v0.2.0
  [46d2c3a1] + MuladdMacro v0.2.1
  [ffc61752] + Mustache v0.5.8
  [a975b10e] + Mux v0.5.3
  [d41bc354] + NLSolversBase v7.1.1
  [2774e3e8] + NLsolve v3.0.1
  [77ba4419] + NaNMath v0.3.2
  [510215fc] + Observables v0.2.3
  [6fe1bfb0] + OffsetArrays v0.9.0
  [bac558e1] + OrderedCollections v1.0.2
  [1dea7af3] + OrdinaryDiffEq v4.17.2
  [d96e819e] + Parameters v0.10.2
  [fa939f87] + Pidfile v1.1.0
  [c84ed2f1] + Ratios v0.3.0
  [3cdcf5f2] + RecipesBase v0.6.0
  [731186ca] + RecursiveArrayTools v0.18.4
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v0.5.2
  [366cf18f] + RigidBodyDynamics v1.2.0
  [e61f16d8] + RigidBodySim v1.0.0
  [f2b01f46] + Roots v0.7.4
  [6038ab10] + Rotations v0.9.1
  [276daf66] + SpecialFunctions v0.7.2
  [90137ffa] + StaticArrays v0.10.0
  [3783bdb8] + TableTraits v0.4.0
  [bd369af6] + Tables v0.1.11
  [a2a6695c] + TreeViews v0.3.0
  [94a5cd58] + TypeSortedCollections v1.0.0
  [30578b45] + URIParser v0.4.0
  [0f1e0344] + WebIO v0.4.2
  [104b5d7c] + WebSockets v1.1.0
  [cc8bc4a8] + Widgets v0.4.3
  [efce3f68] + WoodburyMatrices v0.4.1
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [9abbd945] + Profile
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  Building WebIO ───────────→ `C:\Users\fschmidt\.julia\packages\WebIO\Rk8wc\deps\build.log`
  Building Knockout ────────→ `C:\Users\fschmidt\.julia\packages\Knockout\JIqpG\deps\build.log`
  Building InteractBase ────→ `C:\Users\fschmidt\.julia\packages\InteractBase\Q4IkI\deps\build.log`
  Building LightXML ────────→ `C:\Users\fschmidt\.julia\packages\LightXML\k3mJ4\deps\build.log`
  Building SpecialFunctions → `C:\Users\fschmidt\.julia\packages\SpecialFunctions\fvheQ\deps\build.log`
  Building DiffEqBase ──────→ `C:\Users\fschmidt\.julia\packages\DiffEqBase\nW6r3\deps\build.log`
  Building MbedTLS ─────────→ `C:\Users\fschmidt\.julia\packages\MbedTLS\r1Ufc\deps\build.log`
  Building Blink ───────────→ `C:\Users\fschmidt\.julia\packages\Blink\vKGzM\deps\build.log`
  Building MeshCat ─────────→ `C:\Users\fschmidt\.julia\packages\MeshCat\GlxLQ\deps\build.log`
  Building RigidBodySim ────→ `C:\Users\fschmidt\.julia\packages\RigidBodySim\ZC9wn\deps\build.log`
┌ Error: Error building `RigidBodySim`:
│ WARNING: could not import Base.quit into AtomShell
│ ERROR: LoadError: IOError: could not spawn `7z x electron-v2.0.5-win32-x64.zip -oatom`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:367
│  [2] (::getfield(Base, Symbol("##494#495")){Cmd})(::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:509
│  [3] setup_stdio(::getfield(Base, Symbol("##494#495")){Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:490
│  [4] #_spawn#493(::Nothing, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:508
│  [5] _spawn at .\process.jl:504 [inlined]
│  [6] #run#504(::Bool, ::Function, ::Cmd) at .\process.jl:662
│  [7] run at .\process.jl:661 [inlined]
│  [8] (::getfield(Blink.AtomShell, Symbol("##1#2")))() at C:\Users\fschmidt\.julia\packages\Blink\vKGzM\src\AtomShell\install.jl:48
│  [9] cd(::getfield(Blink.AtomShell, Symbol("##1#2")), ::String) at .\file.jl:85
│  [10] install() at C:\Users\fschmidt\.julia\packages\Blink\vKGzM\src\AtomShell\install.jl:27
│  [11] top-level scope at none:0
│  [12] include at .\boot.jl:317 [inlined]
│  [13] include_relative(::Module, ::String) at .\loading.jl:1044
│  [14] include(::Module, ::String) at .\sysimg.jl:29
│  [15] include(::String) at .\client.jl:392
│  [16] top-level scope at none:0
│ in expression starting at C:\Users\fschmidt\.julia\packages\RigidBodySim\ZC9wn\deps\build.jl:2
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

(v1.0) pkg>
</pre>

**Comment by tkoolen** [comment]
> Does the build expect 7z to be on the path?

The Blink dependency does on Windows, yes:

https://github.com/JunoLab/Blink.jl/blob/f48c6ac6d33a1a3b3d0e88e8bf278da4fc22f9d4/src/AtomShell/install.jl#L48

I guess the AppVeyor build servers do have that installed by default. 

This requirement could be documented better (also on Blink.jl's end). Would be even nicer if their build script also downloaded `7zip` if it's not on the path. For now just install it manually.

**Comment by tkoolen** [comment]
Ref https://github.com/JunoLab/Blink.jl/issues/148.

**Comment by tkoolen** [comment]
This seems to have been addressed in https://github.com/JunoLab/Blink.jl/pull/177. I'll close this; let me know if there are still issues.
